services:
  server:
    image: nginx:alpine
    restart: always
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=www.${DOMAIN},${DOMAIN}
      - LETSENCRYPT_HOST=www.${DOMAIN},${DOMAIN}

networks:
  nginx-proxy:
    external: true
